name: nextpnr-kintex
base: core20
version: '0.1'
summary: yosys+nextpnr FPGA toolchain with support for Kintex FPGAs
description: |
  Pre-packaged toolchain with yosys+nextpnx-xilinx with support for
  Kintex FPGAs
grade: devel
confinement: classic

build-packages:
  - build-essential
  - clang
  - bison
  - flex
  - cmake
  - git
  - libreadline-dev
  - gawk
  - tcl-dev
  - libffi-dev
  - pkg-config
  - python3
  - python3-dev
  - libpython3-dev
  - python3-pip
  - python3-yaml
  - libboost-all-dev
  - zlib1g-dev
  - libeigen3-dev
  - curl

parts:
  pyjson:
    source: https://github.com/Kijewski/pyjson5.git
    plugin: nil
    source-type: git
    source-depth: 1
    stage-packages:
      - python3
      - python3-pip
      - python3-yaml
    override-build: |
      ln -sf /usr/bin/python3 /usr/bin/python
      pip3 install -r requirements-dev.txt
      pip3 install -r requirements-readthedocs.txt
      make
      make install

  prjxray:
    after: [pyjson]
    source: https://github.com/kintex-chatter/prjxray.git
    source-type: git
    source-depth: 1
    source-branch: k7-iob18
    plugin: cmake
    cmake-parameters:
      - -DALLOW_ROOT=1
      - -DCMAKE_INSTALL_PREFIX=/usr

  prjxray-python:
    after: [prjxray]
    source: /root/parts/prjxray/src
    source-type: local
    requirements:
      - requirements.txt
    plugin: python

  nextpnr-xilinx:
    after: [prjxray-python]
    source: https://github.com/kintex-chatter/nextpnr-xilinx.git
    source-type: git
    source-depth: 1
    source-branch: iob18-trial
    plugin: cmake
    stage-packages:
      - libboost-filesystem1.71.0
      - libboost-iostreams1.71.0
      - libboost-program-options1.71.0
      - libboost-python1.71.0
      - libboost-thread1.71.0
      - libgomp1
      - libpython3.8
        
    cmake-parameters:
      - -DARCH=xilinx
      - -DBUILD_GUI=0
      - -DCMAKE_INSTALL_PREFIX=/usr
    override-build: |
      if [ ! -d db-workspace-for-kintex7 ]; then
        git clone https://github.com/kintex-chatter/db-workspace-for-kintex7.git
      fi
      cp -rv db-workspace-for-kintex7/* ../src/xilinx/external/prjxray-db/kintex7
      snapcraftctl build
      cp bbasm ../install/usr/bin/

  bbaexport:
    after: [nextpnr-xilinx]
    source: /root/parts/nextpnr-xilinx/src/xilinx/python
    source-type: local
    plugin: dump
    organize:
      '*' : /opt/bbaexport/

  metadata:
    after: [nextpnr-xilinx]
    source: /root/parts/nextpnr-xilinx/src/xilinx/external/nextpnr-xilinx-meta
    source-type: local
    plugin: dump
    organize:
      '*' : /opt/metadata/

apps:
  nextpnr-xilinx:
    command: usr/bin/nextpnr-xilinx
  bbasm:
    command: usr/bin/bbasm
  prjxray-fasm:
    command: bin/fasm
  prjxray-fasm2frames:
    command: bin/fasm2frames
  prjxray-xc7frames2bit:
    command: usr/bin/xc7frames2bit
