name: nextpnr-kintex
base: core20
version: '0.1.4'
summary: nextpnr PnR FPGA toolchain for Xilinx 7 series FPGAs, with Kintex support
description: |
  Pre-packaged toolchain nextpnx-xilinx with support for Xilinx 7 series FPGAs
  (Spartan7, Artix7, Kintex7)
  Includes support for Kintex FPGAs
  This package does not include Yosys, which needs to be installed separately.
grade: devel
confinement: classic

build-packages:
  - build-essential
  - clang
  - bison
  - flex
  - cmake
  - git
  - libreadline-dev
  - gawk
  - gfortran
  - tcl-dev
  - libffi-dev
  - pkg-config
  - python3
  - python3-dev
  - libpython3-dev
  - python3-pip
  - python3-yaml
  - libboost-all-dev
  - zlib1g-dev
  - libeigen3-dev
  - curl

parts:
  pyjson:
    source: https://github.com/Kijewski/pyjson5.git
    plugin: nil
    source-type: git
    source-depth: 1
    stage-packages:
      - python3
      - python3-pip
      - python3-yaml
    override-build: |
      ln -sf /usr/bin/python3 /usr/bin/python
      pip3 install -r requirements-dev.txt
      pip3 install -r requirements-readthedocs.txt
      make
      make install

  prjxray:
    after: [pyjson]
    source: https://github.com/f4pga/prjxray.git
    source-type: git
    source-depth: 1
    source-branch: master
    plugin: cmake
    cmake-parameters:
      - -DALLOW_ROOT=1
      - -DCMAKE_INSTALL_PREFIX=/usr
    override-build: |
      [ -d prjxray-db ] || git clone https://github.com/SymbiFlow/prjxray-db.git
      snapcraftctl build

  prjxray-python:
    after: [prjxray]
    source: ../parts/prjxray/src
    source-type: local
    requirements:
      - requirements.txt
    python-packages:
      - wheel
    plugin: python
    override-build: |
      pip3 install ../src/third_party/fasm/
      snapcraftctl build
    override-prime: |
      rm -v usr/lib/python3/dist-packages/fasm*egg* || true
      rm -v lib/python3.8/site-packages/fasm*egg* || true
      cp -rv /usr/local/lib/python3.8/dist-packages/fasm usr/lib/python3/dist-packages/
      cp -rv ../stage/lib/python3.8/site-packages/prjxray usr/lib/python3/dist-packages/
      snapcraftctl prime

  nextpnr-xilinx:
    after: [prjxray-python]
    source: https://github.com/gatecat/nextpnr-xilinx.git
    source-type: git
    source-depth: 1
    source-branch: xilinx-upstream
    plugin: cmake
    stage-packages:
      - libboost-filesystem1.71.0
      - libboost-iostreams1.71.0
      - libboost-program-options1.71.0
      - libboost-python1.71.0
      - libboost-thread1.71.0
      - libgomp1
      - libpython3.8
        
    cmake-parameters:
      - -DARCH=xilinx
      - -DBUILD_GUI=0
      - -DCMAKE_INSTALL_PREFIX=/usr
    override-build: |
      rm -rf ../src/xilinx/external/prjxray-db/
      if [ -d ../../prjxray/build/prjxray-db ]; then cp -r ../../prjxray/build/prjxray-db ../src/xilinx/external/; fi
      if [ ! -d db-workspace-for-kintex7 ]; then
        git clone https://github.com/kintex-chatter/db-workspace-for-kintex7.git
      fi
      cp -rv db-workspace-for-kintex7/* ../src/xilinx/external/prjxray-db/kintex7
      pushd ../src/xilinx/external/prjxray-db/kintex7
      ln -s xc7k480t xc7k420t
      popd
      snapcraftctl build
      cp bbasm ../install/usr/bin/

  bbaexport:
    after: [nextpnr-xilinx]
    source: ../parts/nextpnr-xilinx/src/xilinx/
    source-type: local
    plugin: dump
    organize:
      'python/*' : /opt/nextpnr-xilinx/python/
      'constids.inc' : /opt/nextpnr-xilinx/
    stage:
      - opt/nextpnr-xilinx/python/*
      - opt/nextpnr-xilinx/constids.inc

  metadata:
    after: [nextpnr-xilinx]
    source: ../parts/nextpnr-xilinx/src/xilinx/external/nextpnr-xilinx-meta
    source-type: local
    plugin: dump
    organize:
      '*' : /opt/nextpnr-xilinx/external/nextpnr-xilinx-meta/

  prjxray-db:
    after: [nextpnr-xilinx]
    source: ../parts/nextpnr-xilinx/src/xilinx/external/prjxray-db
    source-type: local
    plugin: dump
    organize:
      '*' : /opt/nextpnr-xilinx/external/prjxray-db/

  prjxray-utils:
    after: [prjxray-db]
    source: ../parts/prjxray/src/utils/
    source-type: local
    plugin: dump
    organize:
      '*' : /opt/prjxray/utils/
    override-prime: |
      snapcraftctl prime
      sed -i '5i sys.path.append("/snap/nextpnr-kintex/current/opt/prjxray/")' bin/fasm2frames
      sed -i '6i sys.path.append("/snap/nextpnr-kintex/current/usr/lib/python3/dist-packages/")' bin/fasm2frames
      sed -i '5i sys.path.append("/snap/nextpnr-kintex/current/usr/lib/python3/dist-packages/")' bin/fasm
      sed -i '13i import sys; sys.path.append("/snap/nextpnr-kintex/current/usr/lib/python3/dist-packages/")' opt/prjxray/utils/fasm2frames.py
      sed -i '14i sys.path.append("/snap/nextpnr-kintex/current/opt/prjxray/")' opt/prjxray/utils/fasm2frames.py
      cp bin/fasm2frames bin/bit2fasm
      sed -i '1,$s/from utils.fasm2frames/from utils.bit2fasm/g' bin/bit2fasm

apps:
  nextpnr-xilinx:
    command: usr/bin/nextpnr-xilinx
  bbasm:
    command: usr/bin/bbasm
  fasm:
    command: bin/fasm
  fasm2frames:
    command: bin/fasm2frames
  bit2fasm:
    command: bin/bit2fasm
  xc7frames2bit:
    command: usr/bin/xc7frames2bit
